apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: token-orchastrator-argo-application
spec:
  project: default
  source:
    path: dev/
    repoURL: 'https://github.com/Harsh4902/argocd-app-config'
    targetRevision: HEAD
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
